In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
import sklearn
from time import time
import numpy.linalg as lin
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from scipy import linalg
#print(os.listdir("../input"))
import tensorflow as tf
import numpy as np
#import mnist_handler
import os
import pandas as pd
import matplotlib.pyplot as plt
#os.environ["CUDA_VISIBLE_DEVICES"]="3"; 
INPUT_DIMENSION = 7129
NUM_CLASSES = 2
train_dataset = np.array(pd.read_csv("UCI dataset/leu.t", header = None,delimiter=' '))
test_dataset = np.array(pd.read_csv("UCI dataset/leu",header = None, delimiter=' '))
print(train_dataset.shape)
label = train_dataset[:,0]
data = train_dataset[:,2:]
label = label.reshape(label.shape[0], 1)
print(data)
data1 = []
for i in data:
    data2 = []
    for j in i:
        [_, value] = j.split(":")
        data2.append(value)
    data1.append(data2)
    
data = np.array(data1)

label1 = test_dataset[:,0]
test_data = test_dataset[:,2:]
label1 = label1.reshape(label1.shape[0], 1)
print(test_data)
dat = []
for i in test_data:
    data2 = []
    for j in i:
        [_, value] = j.split(":")
        data2.append(value)
    dat.append(data2)
    
test_data = np.array(dat)
#data = np.concatenate((label, data), axis = 1)

label1.shape




/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


(34, 7131)
[['1:-1.382400' '2:0.062875' '3:0.622518' ... '7127:1.178050'
  '7128:-0.348865' '7129:0.084596']
 ['1:0.651922' '2:-0.354764' '3:2.296340' ... '7127:0.232365'
  '7128:-0.643625' '7129:0.824816']
 ['1:0.654087' '2:1.413430' '3:0.225929' ... '7127:1.569970'
  '7128:-0.466704' '7129:0.539913']
 ...
 ['1:1.096040' '2:1.643850' '3:0.681936' ... '7127:0.973412'
  '7128:-0.264428' '7129:1.837500']
 ['1:0.503660' '2:0.426793' '3:0.294282' ... '7127:0.036783'
  '7128:-0.541209' '7129:0.358362']
 ['1:-0.455835' '2:-0.071517' '3:-0.526423' ... '7127:-0.110748'
  '7128:-0.339931' '7129:-0.068667']]
[['1:-1.462360' '2:-0.645135' '3:-0.835925' ... '7127:-0.596842'
  '7128:-0.471106' '7129:-0.959575']
 ['1:-0.664799' '2:0.206146' '3:-0.368575' ... '7127:-0.865241'
  '7128:-0.664888' '7129:-0.543433']
 ['1:-0.200487' '2:0.379941' '3:-2.382780' ... '7127:-0.496304'
  '7128:-0.433475' '7129:-0.896774']
 ...
 ['1:-1.298680' '2:-1.317620' '3:0.298352' ... '7127:-1.029130'
  '7128:-0.466400' '7

(38, 1)

In [2]:
label1 = np.where(label1==-1, 0, label1)
label2 = np.where(label1==1.0, 1, label1)
print(label2.shape)
test_data = np.concatenate((label2, test_data), axis = 1)

print(test_data.shape)
tr_lab = np.where(label==-1, 0, label)
tr_label = np.where(tr_lab==1.0, 1, tr_lab)
#print(tr_label)
train_data = np.concatenate((tr_label, data), axis = 1)
print(train_data.shape)

total = np.concatenate((train_data,test_data),axis = 0)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(total)
total = scaler.transform(total)
total.shape

(38, 1)
(38, 7130)
(34, 7130)


/usr/lib/python3/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


(72, 7130)

In [3]:
x_train = total[0:38,1:]
y_train = total[0:38,0]
y_train = np.array(y_train, dtype=np.int16)
x_test = total[38:,1:]
y_test = total[38:,0]
y_test = np.array(y_test, dtype=np.int16)
print(x_train.shape)
print(x_test.shape)
print(y_train)
print(y_test.shape)

(38, 7129)
(34, 7129)
[1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1]
(34,)


In [4]:
x_train = total[0:38,1:]
y_train = total[0:38,0]
y_train = np.array(y_train, dtype=np.int16)
x_test = total[38:,1:]
y_test = total[38:,0]
y_test = np.array(y_test, dtype=np.int16)
print(x_train.shape)
print(x_test.shape)
print(y_train)
print(y_test.shape)

(38, 7129)
(34, 7129)
[1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1]
(34,)


In [6]:
#Training = np.concatenate((tr_lab.T,tr_fea ), axis=1)
#Testing = np.concatenate((ts_lab.T,ts_fea ), axis=1)
#print(Testing.shape)
C1 = 2**(-13)
print(C1)
Number_of_Hidden_Neurons = 10

loop = 2
Regression = 0
fdafe = 0
T = y_train
print(T.shape)
orgT = T
P = x_train
print(P.shape)
num_of_input_neuron = 7129
Test_t = y_test
Test_p = x_test
print(Test_t.shape)
orgtT = Test_t
print(num_of_input_neuron)

0.0001220703125
(38,)
(38, 7129)
(34,)
7129


In [7]:
number_of_train_data = T.size
print(number_of_train_data)
number_of_test_data = Test_t.size
print(number_of_test_data)

38
34


In [8]:
def one_hot(y, classes):
    I = np.eye(classes)
    #print(I)
    ret = []
    l = 0
    for y_ in y:
        ret.append(I[y_])
            
    return np.array(ret)
    
temp_T = one_hot(y_train, 2)
temp_Test_t = one_hot(y_test,2)
T = temp_T
Test_t = temp_Test_t


In [9]:
start_train_time = time()
T = P
Test_t = Test_p
kkk = 2
#print(P.shape)
#print(Test_p.shape)
#P = T
for k in range(kkk):
    if(k==0):
        count = 1
    else:
        count = 1
    for nxh in range(count):
        if(k==0):
            bias_weight = np.random.uniform(size=(Number_of_Hidden_Neurons,1))
            BiasofHiddenNeurons1= linalg.orth(bias_weight)
            BBP = BiasofHiddenNeurons1
            print('BBP')
            print(BBP.shape)
            input_weight = np.random.uniform(size=(Number_of_Hidden_Neurons,num_of_input_neuron))*2 -1
            if(Number_of_Hidden_Neurons>num_of_input_neuron):
                input_weight = linalg.orth(input_weight)
                I = input_weight.dot(input_weight.T)
                print(I)
            else:
                input_weight = linalg.orth(input_weight.T)
                print("weight")
                I = input_weight.dot(input_weight.T)
                #print(I)
                #print(input_weight)
                #print(P.shape)
                #print(Test_p.shape)
                #print("update k")
                #print(k)
            concate =  np.concatenate((P.T, Test_p.T), axis=1)
            YYM_H = input_weight.T.dot(concate)
            #print("YYM_H")
            #print(YYM_H.shape)
            YYM_tempH = YYM_H + BBP
            #print(YYM_tempH.shape)
        
        else:
            P = P_save
            #print("P ar ager maan")
            #print(P.shape)
            input_weight = YYM
            #print('again i')
            I = input_weight.dot(input_weight.T)
            #print(I)
            fdafe = 0
            #print("concate for k =1")
            #print(k)
            concate =  np.concatenate((P.T, Test_p.T), axis=1)
            #print("con")
            #print(concate.shape)
            YYM_H = input_weight.dot(concate)
            YM_tempH = YYM_H + BBP
            print("YM_tem")
            print(YM_tempH.shape)
        type1 =0
        if(type1 ==1):
            YYM_H = np.sin(YYM_tempH)
        else:
            YYM_H = YYM_tempH
            print("type1=0,so YYM_H updated bt YYM_tempH")
            print(YYM_H.shape)
            deep_features = YYM_H
        scaler = MinMaxScaler(feature_range=(-1,1))
        scaler.fit(YYM_H)
        Y222 = scaler.transform(YYM_H)
        #print("new")
        #print(Y222)
        H = Y222[:,0:number_of_train_data]
        print("H for 200 data")
        #print(H)
    P_save = P
    P = H
    FT = np.zeros((3,17766))
    E1 = T
    for i in range(1):
        Y2 = E1
        scaler = MinMaxScaler(feature_range=(-1,1))
        scaler.fit(Y2)
        #print(scaler.data_min_)
        Y22 = scaler.transform(Y2)
        #if(Y22.item(i))
        Y2 = Y22
        #print("Y2")
        #print(Y2)
        #Y2 = Y2.astype(float) 
        #i = 0
        x = np.float32(Y2)
        Y4 = np.arcsin(x)
        #print(Y4.shape)
        Y4 = np.real(Y4)
        #e = np.isnan(Y4)
        #print(e)
        #print("Y4 is arcsined")
        #print(Y4)
        if(fdafe==0):
            I = np.eye(Number_of_Hidden_Neurons)
            m = np.eye(Number_of_Hidden_Neurons)/C1 + P.dot(P.T)
            n = P.dot(Y4)
            s = P.dot(P.T)
            #print(s.shape)
            #print(m)
            #print(n.shape)
            g = lin.solve(m,n)
            YYM = g
            print(YYM.shape)
            print("YYM is eyed ")
            #print(YYM)
           # print(P.shape)
            YJX = (P.T).dot(YYM) #hbeta
            #print("YJX = P.dot(YYM)shape")
            #print(YJX.shape)
        else:
            #print("fdafe = 1")
            YJX = P.dot(YYM)
        GXZ111 = (P.T).dot(YYM) 
        GXZ2 = np.sin(GXZ111.T)
        #print("GXZ2")
        #print(GXZ2.shape)
        #GXZ2 = np.float32(GXZ2)
        #print(scale.data_min_)
        FYY = scaler.inverse_transform(GXZ2.T)
        #scaler = StandardScaler()
        #scaler.fit(FYY)
        #FYY = scaler.transform(FYY)
        #print("reversed maxmin")
        #print(FYY.shape)
        GXZ2.shape
        FT1 = FYY
        E1 = E1-FT1
        #print("E1 = E1-FT1")
        print("E1",E1.shape)
        if(i==0):
            FT = FT1
        else:
            FT = FT +FT1
        if(i==0):
            fdafe = 1
        PP = P
    end_train_time = time()
    Training_time = end_train_time - start_train_time
    print(Training_time)
    
    
        
                
                

        
            
            
        


BBP
(10, 1)
weight
type1=0,so YYM_H updated bt YYM_tempH
(10, 72)
H for 200 data
(10, 7129)
YYM is eyed 
E1 (38, 7129)
0.3874061107635498
YM_tem
(10, 72)
type1=0,so YYM_H updated bt YYM_tempH
(10, 72)
H for 200 data
(10, 7129)
YYM is eyed 
E1 (38, 7129)
0.4053213596343994


In [12]:
#m = ((np.eye(Number_of_Hidden_Neurons)/C1)+ P.dot(P.T)))
e =P.dot(P.T)
print(e.shape)
len(P)
P.shape
ind = np.ones((1,1))
orgT = orgT * ind
orgtT = orgtT * ind
#np.eye(Number_of_Hidden_Neurons)/C1 + P.dot(P.T)

(10, 10)


In [14]:
i = 0
#print(P.shape)
#print(orgtT.shape)
Training = np.concatenate((np.int16(orgT), P), axis=0)
#print(Training)
#print(Training.shape)
H_test =Y222[:,number_of_train_data:]
print(H_test.shape)
Testing = np.concatenate((orgtT, H_test), axis=0)
#print(Testing)
GXZ111 = (H_test.T).dot(YYM)
GXZ2 = np.sin(GXZ111.T)
print(GXZ2.shape)
FYY = scaler.inverse_transform(GXZ2.T)
#print("1")
#print(FYY)
#print('test')
#print(Test_t)
TY2 = FYY
mse = mean_squared_error(TY2,Test_t)
Testing_accuracy = np.sqrt(mse)
print(Testing_accuracy)

(10, 34)
(7129, 34)
0.23818335815898523



#### 

In [15]:
deep_features

array([[ 5.26714351e-01,  4.53396227e-01,  3.63334018e-01,
         7.81671205e-01,  4.04165270e-01,  4.50933416e-01,
         4.89073744e-01,  4.52099091e-01,  6.57979206e-01,
         6.91461201e-01,  6.50161074e-01,  7.34241434e-01,
         3.98442160e-01,  1.52517361e-01,  4.33113100e-01,
         2.05117636e-01,  5.22052334e-01,  2.92807504e-01,
         3.95376955e-01,  3.46426896e-01,  4.72924843e-01,
         3.15723173e-01,  6.53887200e-01,  4.08759250e-01,
         3.45653715e-01,  6.96719142e-02,  5.31618672e-01,
         4.21839197e-01,  3.33356507e-01,  5.44393274e-01,
         5.45051966e-01,  6.58267692e-01,  6.61921291e-01,
         5.45405585e-01,  5.62805898e-01,  5.30366371e-01,
         6.87938466e-01,  6.48817055e-01,  6.52608584e-01,
         3.63455875e-01,  6.74513048e-01,  1.03451169e+00,
         4.65811920e-01,  3.63240728e-01,  4.90350914e-01,
         5.78468360e-01,  4.91682521e-01,  5.39949564e-01,
         3.78023122e-01,  4.83240755e-01,  8.45563679e-0

In [20]:
x_train_features = deep_features[:,0:number_of_train_data]
x_test_features = deep_features[:,number_of_train_data:]

In [21]:
x_train_features.shape
x_test_features.shape

(10, 34)

In [23]:
from ELM import ELM 
tf.reset_default_graph()
# ===========================================
# Instantiate os-elm
# ===========================================

    
def one_hot(y, classes):
    I = np.eye(classes)
    ret = []
    for y_ in y:
        ret.append(I[y_])
    return np.array(ret)
    
y_train_onehot = one_hot(y_train, 2)
y_test_onehot = one_hot(y_test, 2)
    
model = ELM(n_input_nodes=10,
                    n_hidden_nodes=1000,
                    n_output_nodes=2,
                    loss='mean_squared_error',
                    activation='sigmoid',
                    name='elm',
                    )
   
#feature_train = tr_data
#feature_test = ts_data
feature_train = x_train_features.T
feature_test = x_test_features.T

model.fit(feature_train, y_train_onehot)

test_loss, test_acc = model.evaluate(feature_test, y_test_onehot, metrics=['loss', 'accuracy'])
print('test_loss: %f' % test_loss)
print('test_acc: %f' % test_acc)
#accuracy_sum+=test_acc

pred = model.predict(feature_test)
test_accuracy = np.sum(np.equal(np.argmax(pred,axis=1), np.argmax(y_test_onehot,axis=1)))/len(y_test_onehot)
print(test_accuracy)
print(np.argmax(pred[:100],axis=1))
print(np.argmax(y_test_onehot[:100],axis=1))

test_loss: 0.600242
test_acc: 0.500000
0.5
[1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
