In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
import sklearn
from time import time
import numpy.linalg as lin
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from scipy import linalg
#print(os.listdir("../input"))
data = pd.read_csv("face-2.csv",header = None)
data = data.astype(float)
print(data)
np.set_printoptions(precision=4)
np.random.seed(333)
data.shape

        0      1      2      3      4      5      6      7      8      9    \
0      75.0  110.0   77.0   48.0  121.0  133.0   80.0   31.0   59.0   92.0   
1      83.0  108.0   75.0   53.0  116.0  133.0   78.0   32.0   53.0   94.0   
2      83.0  120.0   65.0   58.0  119.0  138.0   79.0   32.0   60.0   89.0   
3      74.0  127.0   53.0   55.0  119.0  141.0   84.0   31.0   59.0   93.0   
4      81.0  130.0   49.0   57.0  120.0  138.0   86.0   33.0   55.0  108.0   
5      76.0  142.0   50.0   52.0  127.0  139.0   75.0   32.0   53.0  121.0   
6      75.0  162.0   47.0   45.0  141.0  137.0   72.0   31.0   53.0  125.0   
7      64.0  169.0   43.0   34.0  141.0  138.0   68.0   29.0   53.0  125.0   
8      60.0  171.0   48.0   20.0  141.0  143.0   69.0   28.0   50.0  125.0   
9      64.0  166.0   64.0   29.0  140.0  146.0   74.0   27.0   50.0  128.0   
10     69.0  160.0   90.0   44.0  140.0  138.0   83.0   28.0   51.0  129.0   
11     71.0  162.0  136.0   54.0  142.0  128.0   83.0   29.0   5

(4096, 400)

In [2]:
label = np.empty(0)
ind = np.ones((1,1))
for i in range(40):
    m = i* np.ones((1,10))
    
    
    label = np.append([[label]],[[m]])
    label = label * ind
#print(label.T)  
data1 = data.T
data1.shape




(400, 4096)

In [3]:
scaler = MinMaxScaler(feature_range=(0,1))
scaler.fit(data)
num_array = scaler.transform(data)
array1 = np.float16(num_array)
#fae = np.empty(0)
#array1 = np.set_printoptions(precision=4)
print(array1)
#print(num_array.shape)
#print(label.shape)
fae = np.concatenate((label.T, array1.T), axis=1)

print(fae)
fae.shape

[[0.2864 0.497  0.2961 ... 0.5854 0.1611 0.5464]
 [0.3281 0.4856 0.2864 ... 0.575  0.1444 0.5464]
 [0.3281 0.554  0.2379 ... 0.544  0.1555 0.5464]
 ...
 [0.1146 0.0685 0.1019 ... 0.171  0.6665 0.378 ]
 [0.1042 0.0571 0.1068 ... 0.1917 0.6724 0.3489]
 [0.0938 0.08   0.1019 ... 0.1969 0.683  0.3604]]
[[ 0.      0.2864  0.3281 ...  0.1146  0.1042  0.0938]
 [ 0.      0.4971  0.4856 ...  0.0685  0.0571  0.08  ]
 [ 0.      0.2961  0.2864 ...  0.1019  0.1068  0.1019]
 ...
 [39.      0.5854  0.5752 ...  0.171   0.1917  0.1969]
 [39.      0.1611  0.1444 ...  0.6665  0.6724  0.6831]
 [39.      0.5464  0.5464 ...  0.3779  0.3489  0.3604]]


(400, 4097)

In [4]:
nclass = fae.max()
nclass = np.int16(nclass) + 1
print(nclass)
label = fae[:,0]
label = (label *ind).T
tr_idx = np.empty(0)
ts_idx = np.empty(0)
i = 0
#label.astype(int)
#print(label)
#k =label.item(34)
#print(k)
#label.astype(int)
#print(type(idx_label))
count = 0
#array = np.empty(0,dtype = np.int)
#array.astype(int)
#array = np.insert(array,0,count)
#print(array)
#for j in range(nclass):
count = 0
#j = 0
ts_idx = np.empty(0)
tr_idx = np.empty(0)
#print(label.shape)
for j in range(nclass):
   # print(j)
    #print(label.item(i))
    idx_label = np.empty(0,dtype = np.int16)
    while(i < label.shape[0] and j == label.item(i)):
        #print(count )
        #print(idx_label)
        idx_label = np.append(idx_label,count)
        #print(idx_label)
        count = count +1
        i = i+1
        
    #print("idx_label")
    #print(idx_label)
    #unique_label = idx_label
   # print(unique_label)
    length = idx_label.size
    tr_num = 5
    np.random.shuffle(idx_label) 
    tr_idx = np.append([[tr_idx]],[[idx_label[0:tr_num]]])
    ts_idx = np.append([[ts_idx]],[[idx_label[tr_num:length]]])
print(ts_idx)


40
[  4.   7.   6.   9.   3.  18.  15.  11.  19.  14.  28.  21.  25.  29.
  23.  31.  30.  37.  32.  38.  44.  49.  48.  43.  45.  53.  51.  59.
  54.  58.  68.  69.  65.  61.  64.  72.  74.  79.  77.  73.  88.  87.
  80.  85.  82.  94.  99.  96.  91.  90. 101. 109. 105. 108. 106. 112.
 116. 117. 114. 113. 120. 128. 126. 124. 129. 136. 135. 132. 138. 133.
 146. 143. 140. 149. 142. 152. 157. 151. 154. 155. 166. 165. 167. 162.
 169. 177. 176. 171. 178. 179. 189. 188. 186. 185. 181. 192. 196. 198.
 193. 190. 200. 202. 209. 205. 201. 218. 216. 217. 219. 215. 224. 229.
 225. 223. 222. 231. 234. 233. 239. 235. 248. 244. 241. 249. 242. 251.
 253. 254. 255. 258. 267. 264. 261. 268. 263. 270. 275. 272. 273. 279.
 286. 280. 281. 288. 283. 297. 294. 293. 290. 292. 300. 309. 305. 303.
 302. 312. 317. 319. 311. 310. 320. 324. 327. 325. 322. 333. 338. 332.
 330. 331. 344. 341. 346. 340. 342. 350. 358. 352. 353. 356. 367. 364.
 361. 369. 362. 376. 372. 374. 370. 377. 386. 387. 384. 388. 385. 391.
 39

In [5]:
tr_idx = tr_idx.astype(int)
ts_idx = ts_idx.astype(int)

tr_fea = fae[tr_idx,1:]
tr_lab = fae[[tr_idx],0]
ts_fea = fae[ts_idx,1:]
ts_lab = fae[[ts_idx],0]

print(ts_fea.shape)
print(ts_lab)

(200, 4096)
[[ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  2.  2.  2.  2.  2.  3.  3.  3.
   3.  3.  4.  4.  4.  4.  4.  5.  5.  5.  5.  5.  6.  6.  6.  6.  6.  7.
   7.  7.  7.  7.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9. 10. 10. 10. 10.
  10. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 13. 13. 13. 13. 13. 14. 14.
  14. 14. 14. 15. 15. 15. 15. 15. 16. 16. 16. 16. 16. 17. 17. 17. 17. 17.
  18. 18. 18. 18. 18. 19. 19. 19. 19. 19. 20. 20. 20. 20. 20. 21. 21. 21.
  21. 21. 22. 22. 22. 22. 22. 23. 23. 23. 23. 23. 24. 24. 24. 24. 24. 25.
  25. 25. 25. 25. 26. 26. 26. 26. 26. 27. 27. 27. 27. 27. 28. 28. 28. 28.
  28. 29. 29. 29. 29. 29. 30. 30. 30. 30. 30. 31. 31. 31. 31. 31. 32. 32.
  32. 32. 32. 33. 33. 33. 33. 33. 34. 34. 34. 34. 34. 35. 35. 35. 35. 35.
  36. 36. 36. 36. 36. 37. 37. 37. 37. 37. 38. 38. 38. 38. 38. 39. 39. 39.
  39. 39.]]


In [6]:
Training = np.concatenate((tr_lab.T,tr_fea ), axis=1)
Testing = np.concatenate((ts_lab.T,ts_fea ), axis=1)
print(Testing.shape)
C1 = 2**(-13)
print(C1)
Number_of_Hidden_Neurons = 40

loop = 2
Regression = 0
fdafe = 0
T = Training[:,[0]]
print(T.shape)
orgT = T
P = Training[:,1:]
print(P.shape)
num_of_input_neuron = P[0,:].size
Test_t = Testing[:,[0]]
Test_p = Testing[:,1:]
print(Test_t.shape)
orgtT = Test_t
print(num_of_input_neuron)

(200, 4097)
0.0001220703125
(200, 1)
(200, 4096)
(200, 1)
4096


In [7]:
number_of_train_data = T.size
print(number_of_train_data)
number_of_test_data = Test_t.size
print(number_of_test_data)

200
200


In [8]:
target = np.concatenate((T.T, Test_t.T), axis=1)
sorted_target = np.sort(target,axis = 1)
print(sorted_target[0,1])
m =1
unique_label = m* np.ones((1,40))
unique_label[0,0] = sorted_target[0,0]
i = 1
iteration = number_of_train_data + number_of_test_data
print(iteration)
j = 0
while(i<iteration):
    if(sorted_target[0,i]!=unique_label[0,j]):
        j = j+1
        unique_label[0,j]= sorted_target[0,i]
    i = i+1
num_class = j+1
num_of_output_neuron = num_class
#print(num_of_output_neuron)
print(unique_label)
print(num_class)   



0.0
400
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39.]]
40


In [9]:
temp_T = np.zeros((num_of_output_neuron, number_of_train_data))
T = T.T
for i in range(number_of_train_data):
    for j in range(num_class):
        if(unique_label[0,j]==T[0,i]):
            break
    temp_T[j,i]= 1
T = temp_T*2-1
print(T.shape)
y_train = T

(40, 200)


In [10]:
temp_Test_t = np.zeros((num_of_output_neuron, number_of_test_data))
Test_t = Test_t.T
for i in range(number_of_test_data):
    for j in range(num_class):
        if(unique_label[0,j]==Test_t[0,i]):
            break
    temp_Test_t[j,i]= 1
Test_t = temp_Test_t*2 -1
y_test = Test_t
print(Test_t.shape)

(40, 200)


In [11]:
start_train_time = time()
T = P
Test_t = Test_p
kkk = 2
#print(P.shape)
#print(Test_p.shape)
#P = T
for k in range(kkk):
    if(k==0):
        count = 1
    else:
        count = 1
    for nxh in range(count):
        if(k==0):
            bias_weight = np.random.uniform(size=(Number_of_Hidden_Neurons,1))
            BiasofHiddenNeurons1= linalg.orth(bias_weight)
            BBP = BiasofHiddenNeurons1
            print('BBP')
            print(BBP.shape)
            input_weight = np.random.uniform(size=(Number_of_Hidden_Neurons,num_of_input_neuron))*2 -1
            if(Number_of_Hidden_Neurons>num_of_input_neuron):
                input_weight = linalg.orth(input_weight)
                I = input_weight.dot(input_weight.T)
                print(I)
            else:
                input_weight = linalg.orth(input_weight.T)
                print("weight")
                I = input_weight.dot(input_weight.T)
                print(I)
                print(input_weight)
                print(P.shape)
                print(Test_p.shape)
                print("update k")
                print(k)
            concate =  np.concatenate((P.T, Test_p.T), axis=1)
            YYM_H = input_weight.T.dot(concate)
            print("YYM_H")
            print(YYM_H.shape)
            YYM_tempH = YYM_H + BBP
            print(YYM_tempH.shape)
        
        else:
            P = P_save
            print("P ar ager maan")
            print(P.shape)
            input_weight = YYM
            print('again i')
            I = input_weight.dot(input_weight.T)
            print(I)
            fdafe = 0
            print("concate for k =1")
            print(k)
            concate =  np.concatenate((P.T, Test_p.T), axis=1)
            print("con")
            print(concate.shape)
            YYM_H = input_weight.dot(concate)
            YM_tempH = YYM_H + BBP
            
            print(YM_tempH.shape)
        type1 =0
        if(type1 ==1):
            YYM_H = np.sin(YYM_tempH)
        else:
            YYM_H = YYM_tempH
            print("type1=0,so YYM_H updated bt YYM_tempH")
            print(YYM_H.shape)
            deep_features = YYM_H
        scaler = MinMaxScaler(feature_range=(-1,1))
        scaler.fit(YYM_H)
        Y222 = scaler.transform(YYM_H)
        print("new")
        print(Y222)
        H = Y222[:,0:number_of_train_data]
        print("H for 200 data")
        print(H)
    P_save = P
    P = H
    FT = np.zeros((3,17766))
    E1 = T
    for i in range(1):
        Y2 = E1
        scaler = MinMaxScaler(feature_range=(-1,1))
        scaler.fit(Y2)
        #print(scaler.data_min_)
        Y22 = scaler.transform(Y2)
        #if(Y22.item(i))
        Y2 = Y22
        print("Y2")
        print(Y2)
        #Y2 = Y2.astype(float) 
        #i = 0
        x = np.float32(Y2)
        Y4 = np.arcsin(x)
        print(Y4.shape)
        Y4 = np.real(Y4)
        #e = np.isnan(Y4)
        #print(e)
        print("Y4 is arcsined")
        print(Y4)
        if(fdafe==0):
            m = ((np.eye((P[0].size))/C1)+ P.dot(P.T))
            n = P.dot(Y4)
            s = P.dot(P.T)
            print(s.shape)
            print(m)
            print(n.shape)
            g = lin.solve(m,n)
            YYM = g
            print(YYM.shape)
            print("YYM is eyed ")
            print(YYM)
           # print(P.shape)
            YJX = P.dot(YYM) #hbeta
            print("YJX = P.dot(YYM)shape")
            print(YJX.shape)
        else:
            print("fdafe = 1")
            YJX = P.dot(YYM)
        GXZ111 = P.dot(YYM)
        GXZ2 = np.sin(GXZ111.T)
        print("GXZ2")
        print(GXZ2.shape)
        #GXZ2 = np.float32(GXZ2)
        #print(scale.data_min_)
        FYY = scaler.inverse_transform(GXZ2.T)
        #scaler = StandardScaler()
        #scaler.fit(FYY)
        #FYY = scaler.transform(FYY)
        print("reversed maxmin")
        print(FYY.shape)
        GXZ2.shape
        FT1 = FYY
        E1 = E1-FT1
        print("E1 = E1-FT1")
        print("E1",E1.shape)
        if(i==0):
            FT = FT1
        else:
            FT = FT +FT1
        if(i==0):
            fdafe = 1
        PP = P
    end_train_time = time()
    Training_time = end_train_time - start_train_time
    print(Training_time)
    
    
        
                
                

        
            
            
        


BBP
(40, 1)
weight
[[ 8.3665e-03 -2.0314e-03 -1.5032e-03 ...  1.2056e-03 -5.7153e-04
  -2.8869e-03]
 [-2.0314e-03  1.0328e-02  1.8016e-03 ... -1.4990e-03 -1.1538e-03
   8.8224e-04]
 [-1.5032e-03  1.8016e-03  7.5375e-03 ...  3.3647e-04  2.1771e-03
  -1.1105e-03]
 ...
 [ 1.2056e-03 -1.4990e-03  3.3647e-04 ...  1.0943e-02 -3.1644e-05
   7.0917e-04]
 [-5.7153e-04 -1.1538e-03  2.1771e-03 ... -3.1644e-05  8.2599e-03
   9.7631e-04]
 [-2.8869e-03  8.8224e-04 -1.1105e-03 ...  7.0917e-04  9.7631e-04
   8.9893e-03]]
[[-8.4698e-03  1.0662e-02 -2.0786e-02 ... -7.0239e-03  1.6630e-03
  -1.2927e-02]
 [ 1.2257e-03 -3.2636e-02 -1.6177e-02 ... -1.6262e-02  1.1615e-02
   1.2964e-02]
 [-1.4798e-02 -2.5795e-03 -2.1708e-05 ... -4.2140e-03  5.8743e-03
  -1.1547e-02]
 ...
 [-3.8499e-03  1.0020e-02 -5.4798e-03 ...  1.8952e-02 -1.5364e-03
   7.3271e-03]
 [-1.8227e-02  2.3429e-02  2.3147e-02 ...  9.1428e-03  9.6119e-04
  -1.0994e-02]
 [ 5.4901e-03 -1.9448e-03 -1.7766e-02 ...  1.0206e-02 -1.3356e-02
  -3.9007e-03

ValueError: operands could not be broadcast together with shapes (200,200) (40,40) 

In [ ]:
i = 0
#print(P.shape)
#print(orgtT.shape)
Training = np.concatenate((np.int16(orgT), P), axis=1)
print(Training)
print(Training.shape)
H_test =Y222[:,number_of_train_data:]
#print(H_test.shape)
Testing = np.concatenate((orgtT, H_test), axis=1)
#print(Testing)
GXZ111 = H_test.dot(YYM)
GXZ2 = np.sin(GXZ111.T)
print(GXZ2.shape)
FYY = scaler.inverse_transform(GXZ2.T)
#print("1")
print(FYY)
print('test')
print(Test_t)
TY2 = FYY
mse = mean_squared_error(TY2,Test_t)
Testing_accuracy = np.sqrt(mse)
print(Testing_accuracy)

In [12]:
deep_features.shape

(40, 400)

In [13]:
x_train_features = deep_features[:,0:number_of_train_data]
x_test_features = deep_features[:,number_of_train_data:]

In [17]:
x_train_features.shape
y_train_onehot.shape

(200, 40)

In [18]:
from ELM import ELM 
#tf.reset_default_graph()
# ===========================================
# Instantiate os-elm
# ===========================================

    
def one_hot(y, classes):
    I = np.eye(classes)
    ret = []
    for y_ in y:
        ret.append(I[y_])
    return np.array(ret)
    
y_train_onehot = y_train
y_test_onehot = y_test
    
model = ELM(n_input_nodes=200,
                    n_hidden_nodes=1000,
                    n_output_nodes=40,
                    loss='mean_squared_error',
                    activation='sigmoid',
                    name='elm',
                    )
   
#feature_train = tr_data
#feature_test = ts_data
feature_train = x_train_features
feature_test = x_test_features

model.fit(feature_train, y_train_onehot)

test_loss, test_acc = model.evaluate(feature_test, y_test_onehot, metrics=['loss', 'accuracy'])
print('test_loss: %f' % test_loss)
print('test_acc: %f' % test_acc)
#accuracy_sum+=test_acc

pred = model.predict(feature_test)
test_accuracy = np.sum(np.equal(np.argmax(pred,axis=1), np.argmax(y_test_onehot,axis=1)))/len(y_test_onehot)
print(test_accuracy)
print(np.argmax(pred[:100],axis=1))
print(np.argmax(y_test_onehot[:100],axis=1))


test_loss: 0.045722
test_acc: 0.650000
0.65
[  0   5  10  15  20  25 155  35  40  45  50  55 125  80  40  75  80  15
  85  45 100 105   0 115 120 125 133 135 140 145 150 155 160 165 170  20
  40   0  15  65]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195]
